---
- hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
   - name: Copy New Hosts File
     file: 
       src: hosts
       dest: /etc/hosts
       owner: root
       group: root
       mode: '0644'
       
     
